site_name: Hugo BERTAGNA - Doc Website
site_url: https://hugobertagna.github.io/ctf_portfolio/

theme:
  name: material
  palette:
    scheme: slate # Mode sombre
    primary: indigo
  features:
    - navigation.expand # Déplie les menus
    - content.code.copy # Bouton copier
    - navigation.top    # Bouton retour en haut

# Configuration des extensions (Alertes, Code, etc.)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list

# LE MENU DE NAVIGATION
nav:
  - Accueil: index.md
  
  - Root-Me:
      - 'Web - Client':
          - 'Challenge 1 : HTML': rootme/web/challenge1.md
          - 'Challenge 2 : Javascript': rootme/web/challenge2.md
      - 'Web - Serveur':
          - 'SQL Injection': rootme/web-serveur/sqli.md
  
  - TryHackMe:
      - 'Junior Pentester':
          - 'Intro Nmap': tryhackme/junior/nmap.md

  - 'Cours et TP':
      - Cybersécurité:
          # Assure-toi que ce fichier existe bien dans docs/cours-TP/cybersecurite/
          - 'Notions de base': cours-TP/cybersecurite/notions_de_base.md
          
      - 'Systèmes C':
          # Attention aux majuscules : C_Systems doit correspondre à ton dossier
          - 'TP 1 - Apache': cours-TP/C_Systems/tp1/tp1.md
          - 'TP 2 - MySQL': cours-TP/C_Systems/tp2/tp2.md
          - 'TP 3 - Docker': cours-TP/C_Systems/tp3/tp3.md
          - 'TP A': cours-TP/C_Systems/tpa/tpa.md
          - 'TP B': cours-TP/C_Systems/tpb/tpb.md
          - 'TP C': cours-TP/C_Systems/tpc/tpc.md
          - 'TP D': cours-TP/C_Systems/tpd/tpd.md