site_name: Hugo's website
site_url: https://github.com/hugobertagna/ctf_portfolio

theme:
  name: material
  palette:
    scheme: slate # Mode sombre
    primary: indigo
  features:
    - navigation.expand # Ouvre les dossiers automatiquement
    - content.code.copy # Bouton copier pour le code

# C'est ICI que se fait la liaison avec tes .md
nav:
  - Accueil: index.md
  - Root-Me:
    - Programmation: 
        - 'Challenge 1 : TCP - Retour au collège': rootme/Programmation/TCP-RetourAuCollege.md
        - 'Challenge 2 : TCP - Chaîne encodée': rootme/Programmation/TCP-ChaineEncodee.md
    - Systeme:
        - 'Challenge 1 : Bash - System 1 ': rootme/Systeme/Bash-System1.md
  - TryHackMe:
      - 'Intro Nmap': tryhackme/junior/nmap.md
  - Cours:
      - 'Cybersécurité': 
          - 'Notions de base': cours/cybersecurite/notions_de_base.md
          - 'TD 1 - Ingénierie sociale': cours/cybersecurite/TD_Social_Engineering.md
      - 'C System':
          - 'TP_1 - Apache': cours/csystem/tp1/tp1.md
          - 'TP_2 - MySQL / MariaDB': cours/csystem/tp2/tp2.md
          - 'TP_3 - Docker': cours/csystem/tp3/tp3.md
          - 'TP_A - Gestion des processus sous linux': cours/csystem/tpa/tpa.md
          - 'TP_B - Communication Inter Processus': cours/csystem/tpb/tpb.md
          - 'TP_C - Communication Inter Processus II': cours/csystem/tpc/tpc.md
          - 'TP_D - Les Fichiers et Périphériques': cours/csystem/tpd/tpd.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition