nav:
  - Accueil: index.md
  - Root-Me:
    - Programmation: 
        # Vérifie que les fichiers .md sont bien DIRECTEMENT dans le dossier Programmation
        - 'Challenge 1 : TCP - Retour au collège': rootme/Programmation/TCP-RetourAuCollege.md
        - 'Challenge 2 : TCP - Chaîne encodée': rootme/Programmation/TCP-ChaineEncodee.md
    - Systeme:
        # Attention à la majuscule "Systeme" (comme dans ton tree)
        - 'Challenge 1 : Bash - System 1 ': rootme/Systeme/Bash-System1.md
  
  - TryHackMe:
      # Si le fichier est dans un sous-dossier "junior", garde ce chemin. 
      # Sinon, si le fichier est directement dans tryhackme, enlève "/junior"
      - 'Intro Nmap': tryhackme/junior/nmap.md

  - Cours:
      - Cybersécurité: 
          # Le dossier est dans "rootme" d'après ton tree
          - 'Notions de base': rootme\cybersecurite\notions_de_base.md
          - 'TD 1 - Ingénierie sociale': rootme\cybersecurite\TD_Social_Engineering.md
      - 'C System':
          # CORRECTION ICI : "rootme/C_Systems/" + respect des majuscules
          # Je pars du principe que le fichier s'appelle comme le dossier (ex: tp1/tp1.md)
          - 'TP_1 - Apache': rootme/C_Systems/tp1/tp1.md
          - 'TP_2 - MySQL / MariaDB': rootme/C_Systems/tp2/tp2.md
          - 'TP_3 - Docker': rootme/C_Systems/tp3/tp3.md
          - 'TP_A - Gestion des processus': rootme/C_Systems/tpa/tpa.md
          - 'TP_B - Communication IPC': rootme/C_Systems/tpb/tpb.md
          - 'TP_C - Communication IPC II': rootme/C_Systems/tpc/tpc.md
          - 'TP_D - Fichiers et Périphériques': rootme/C_Systems/tpd/tpd.md