site_name: Hugo's website
site_url: https://github.com/hugobertagna/ctf_portfolio

theme:
  name: material
  palette:
    scheme: slate # Mode sombre
    primary: indigo
  features:
    - navigation.expand # Ouvre les dossiers automatiquement
    - content.code.copy # Bouton copier pour le code

# C'est ICI que se fait la liaison avec tes .md
nav:
  - Accueil: index.md
  - Root-Me:
      - 'Challenge 1 : HTML': rootme/challenge1.md
      - 'Challenge 2 : Javascript': rootme/challenge2.md
  - TryHackMe:
      - 'Intro Nmap': tryhackme/junior/nmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition